version: '3'

services:
  mongo:
    image: mongo:3.6.8
    ports:
      - 27017:27017
    network_mode: host


  visualizer:
    build:
      context: .
      dockerfile: DockerfileVisualizer
    # image: ubuntu
    environment:
      - MONGO_URL=mongodb://localhost:27017/dbname
    depends_on:
      - mongo
    container_name: visualizer
    restart: unless-stopped
    ports:
      - "20000:20000"
      - "5000:5000"
    network_mode: host

#  biasdetection:
#    build:
#      context: .
#      dockerfile: DockerfileBiasdetection
#    image: ubuntu
#    container_name: biasdetection
#    restart: unless-stopped
#    ports:
#      - "127.0.0.1:5004:5004"
#    network_mode: host

